language: python

# TODO: http://docs.travis-ci.com/user/languages/python/#PyPy-Support once
# native libraries can be installed.
python:
  - "2.7"
  - "3.3"
  - "3.4"

before_install:
  - sudo apt-get update

install:
  - sudo apt-get install ghc cabal-install git xcb-proto happy alex xvfb libxcb1-dev
  - cabal update
  - git clone https://github.com/tych0/xcb-types.git
  - cd xcb-types
  - cabal install
  - cd ..
  - cabal install --only-dependencies --enable-tests
  - cabal configure --enable-tests
  - pip install -r requirements.txt

script: "make check"
